# devops-pipelines/.github/workflows/multi-app-pipeline.yml
name: Centralized Multi-App Build & Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Kubernetes environment (dev/staging/prod)"
        required: true
        default: "dev"
      tag:
        description: "Docker image tag"
        required: true
        default: "latest"
      registry:
        description: "Docker registry"
        required: true
        default: "docker.io"

jobs:
  build-deploy:
    name: Build & Deploy ${{ matrix.app }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [petclinic, redis, kafka]   # Add or remove apps here

    steps:
      - name: Trigger Build Workflow
        uses: github-org/app-${{ matrix.app }}/.github/workflows/build.yml@main
        with:
          image_name: ${{ matrix.app }}
          tag: ${{ github.event.inputs.tag }}
          registry: ${{ github.event.inputs.registry }}
        secrets: inherit

      - name: Trigger Deploy Workflow
        uses: github-org/app-${{ matrix.app }}/.github/workflows/deploy.yml@main
        with:
          registry: ${{ github.event.inputs.registry }}
          image_name: ${{ matrix.app }}
          tag: ${{ github.event.inputs.tag }}
          environment: ${{ github.event.inputs.environment }}
        secrets: inherit

